include("helpers.jl")
include("nn-greedy-2-regret.jl")
include("greedy-cycle-2-regret.jl")

println("TSPA:")
data_path = "lab1/TSPA.csv"
distance_matrix, costs = prepare_data(data_path)
println("NN 2-Regret")
scores, solutions = test_algorithm(nn_greedy_2_regret, distance_matrix, costs, weights=[1,0])
plot_best_solution(scores, solutions, data_path, "TSPA.csv - NN Greedy 2-Regret", "lab2/TSPA/NN.png")
println("\n")
println("NN 2-Regret with weighted sum criterion")
scores, solutions = test_algorithm(nn_greedy_2_regret, distance_matrix, costs, weights=[1,1])
plot_best_solution(scores, solutions, data_path, "TSPA.csv - NN Weighted 2-Regret", "lab2/TSPA/NN_weighted.png")
println("\n")

println("Greedy Cycle 2-Regret")
scores, solutions = test_algorithm(greedy_cycle_2_regret, distance_matrix, costs, weights=[1,0])
plot_best_solution(scores, solutions, data_path, "TSPA.csv - Greedy Cycle 2-Regret", "lab2/TSPA/GC.png")
println("\n")
println("Greedy Cycle 2-Regret with weighted sum criterion")
scores, solutions = test_algorithm(greedy_cycle_2_regret, distance_matrix, costs, weights=[1,1])
plot_best_solution(scores, solutions, data_path, "TSPA.csv - Greedy Cycle Weighted 2-Regret", "lab2/TSPA/GC_weighted.png")
println("\n")

println("TSPB:")
data_path = "lab1/TSPB.csv"
distance_matrix, costs = prepare_data(data_path)
println("NN 2-Regret")
scores, solutions = test_algorithm(nn_greedy_2_regret, distance_matrix, costs, weights=[1,0])
plot_best_solution(scores, solutions, data_path, "TSPB.csv - NN Greedy 2-Regret", "lab2/TSPB/NN.png")
println("\n")
println("NN 2-Regret with weighted sum criterion")
scores, solutions = test_algorithm(nn_greedy_2_regret, distance_matrix, costs, weights=[1,1])
plot_best_solution(scores, solutions, data_path, "TSPB.csv - NN Weighted 2-Regret", "lab2/TSPB/NN_weighted.png")
println("\n")

println("Greedy Cycle 2-Regret")
scores, solutions = test_algorithm(greedy_cycle_2_regret, distance_matrix, costs, weights=[1,0])
plot_best_solution(scores, solutions, data_path, "TSPB.csv - Greedy Cycle 2-Regret", "lab2/TSPB/GC.png")
println("\n")
println("Greedy Cycle 2-Regret with weighted sum criterion")
scores, solutions = test_algorithm(greedy_cycle_2_regret, distance_matrix, costs, weights=[1,1])
plot_best_solution(scores, solutions, data_path, "TSPB.csv - Greedy Cycle Weighted 2-Regret", "lab2/TSPB/GC_weighted.png")
println("\n")